# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb0a1980854c8f7415ab92d03e27810c13db4dac749fe295991151ff1ce1a1b4e0a76bbceebdcabfeb906b3008f7796fc1d64844691a7044079feab8ef93feb

test:
  secret_key_base: 83fb75aff25ab97ba4a39e9ba192e4f479875c874f73a04c6dd4fb6ea6ee1efb50df21b1fc318130cb2b314928eb6c1bfc747cbbc9c12ba34036bf6bfb8f0446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
